development:
  adapter: postgresql
  host: localhost
  database: tram_development
  password: <%= ENV['TRAM_DEV_DATABASE_PASSWORD'] %>
  username: eugene

test:
  adapter: postgresql
  host: localhost
  database: tram_test
  password: <%= ENV['TRAM_TEST_DATABASE_PASSWORD'] %>
  username: eugene

production:
  adapter: postgresql
  pool: 5
  host: localhost
  encoding: unicode
  host: localhost
  database: tram_production
  username: tram_adapt
  password: <%= ENV['TRAM_ADAPT_DATABASE_PASSWORD'] %>
