default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tram_development

test:
  <<: *default
  database: tram_test

production:
  <<: *default
  host: localhost
  database: tram_production
  username: tram_adapt
  password: <%= ENV['TRAM_DATABASE_PASSWORD'] %>
