development:
  adapter: postgresql
  host: localhost
  database: tram_development
  username: eugene
  password: 1q2w3e4r5t

test:
  adapter: postgresql
  host: localhost
  database: tram_test
  username: eugene
  password: 1q2w3e4r5t

production:
  adapter: postgresql
  pool: 5
  encoding: unicode
  host: localhost
  database: tram_production
  username: tram_adapt
  password: <%= ENV['ADAPT_DATABASE_PASSWORD'] %>
