default: &default
  adapter: postgresql
  username: adapt
  password: <%= ENV['ADAPT_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: adapt_development

test:
  <<: *default
  database: adapt_test

production:
  <<: *default
  pool: 5
  encoding: unicode
  host: localhost
  database: adapt_production